# Generated by Django 5.1.7 on 2025-03-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dim'),
    ]

    operations = [
        migrations.CreateModel(
            name='tty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('years', models.JSONField(default=list)),
            ],
        ),
    ]
